name: Runs publish maven and spark setup in a matrix

on:
  workflow_call:
    inputs:
      theMatrix:
        required: true
        type: string
        description: the json matrix to build against
      storeTarget:
        required: false
        type: string
        description: location of maven target on the matrix build be upload-artifact?
      additionalShellCommand:
        required: false
        type: string
        description: run extra commands on the shell, must be a .sh file location without the extension
      sparkVersion:
        required: false
        type: string
        description: Spark version to use
      sparkScalaVersion:
        required: false
        type: string
        description: Spark scala version to use
      hadoopVersion:
        required: false
        type: string
        description: Hadoop version to use
      jdk:
        required: false
        type: string
        description: jdk version to use
      mvnCliOpts:
        required: false
        type: string
        description: mvn cli opts
      mvnOpts:
        required: false
        type: string
        description: used to set MAVEN_OPTS
    secrets:
      MAVEN_GPG_PRIVATE_KEY:
        required: true
      CENTRAL_USERNAME:
        required: true
      CENTRAL_TOKEN:
        required: true
      MAVEN_GPG_PASSPHRASE:
        required: true

jobs:
  theRun:
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(inputs.theMatrix) }}

    runs-on: ubuntu-latest
    # only publish snapshots on main by default, or when ~cut-release is in the commits
    # needs always per https://github.com/actions/runner/issues/491 very annoying
    # only do snapshots on main by default, releases/snapshots forced with ~cut-release
    if: |
      always() &&
          !contains(needs.*.result, 'failure') &&
          !contains(needs.*.result, 'cancelled') &&
      (contains(github.event.head_commit.message, '~docsOnly') != true) &&
        ( (endsWith(needs.site.outputs.version, '-SNAPSHOT') && github.ref == 'refs/heads/main') ||
          contains(github.event.head_commit.message, '~cut-release') )
    steps:
      - uses: actions/checkout@v4.1.2
        with:
          submodules: recursive
      - uses: sparkutils/spark-maven-action@main
        with:
          title: Build ${{ matrix.profile }},${{ matrix.scala }} with ${{ inputs.testString }}
          script: |
            mvn ${{ inputs.mvnCliOpts }} -DskipTests -Dclassifiers=tests clean deploy -P ${{ matrix.profile }},${{ matrix.scala }}
          gpgKey: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          sparkVersion: ${{ inputs.sparkVersion }}
          sparkScalaVersion: ${{ inputs.sparkScalaVersion }}
          hadoopVersion: ${{ inputs.hadoopVersion }}
          jdk: ${{ inputs.jdk }}
          mvnOpts: ${{ inputs.mvnOpts }}
          mvnCliOpts: ${{ inputs.mvnCliOpts }}
        env:
          CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
          CENTRAL_TOKEN: ${{ secrets.CENTRAL_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
